server {
    listen 80;
    listen [::]:80 default ipv6only=on;

    server_name _;

    root /var/www/html;
    index index.php index.html index.htm;

    access_log /dev/stdout;
    error_log /dev/stderr info;

    sendfile off;

    location /.git {
        deny all;
        return 403;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    location ^~ /.well-known {
        allow all;
        auth_basic off;
    }

    location ~ /\. {
        log_not_found off; 
        deny all;
	}

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
        fastcgi_index index.php;
        include fastcgi_params;
    }

    location ~* \.(jpg|jpeg|gif|png|css|js|ico|webp|tiff|ttf|svg)$ {
        expires 5d;
    }
}